apiVersion: v1
kind: ConfigMap
metadata:
  name: agenticraft-config
  namespace: agenticraft
  labels:
    app: agenticraft-api
data:
  app-config.yaml: |
    service:
      name: agenticraft-api
      version: 1.0.0
    
    cors:
      origins:
        - https://app.agenticraft.example.com
        - http://localhost:3000
      
    rate_limit:
      enabled: true
      requests_per_minute: 100
      
    telemetry:
      enabled: true
      otlp_endpoint: http://otel-collector:4317
      service_name: agenticraft-api
      environment: production
      
    providers:
      default: openai
      available:
        - openai
        - anthropic
        - ollama
        
    tools:
      enabled:
        - search
        - calculator
        - files
        - http
        - text
        
    memory:
      conversation:
        max_messages: 100
        ttl_minutes: 60
      knowledge:
        provider: chromadb
        collection: agenticraft
        
    logging:
      level: INFO
      format: json
      
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
      
    scrape_configs:
      - job_name: 'agenticraft-api'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - agenticraft
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
