site_name: AgentiCraft
site_url: https://agenticraft.github.io/agenticraft/
site_description: Production-ready AI agent framework with dynamic provider switching
site_author: AgentiCraft Team

repo_name: agenticraft/agenticraft
repo_url: https://github.com/agenticraft/agenticraft
edit_uri: edit/main/docs/

copyright: Copyright &copy; 2025 AgentiCraft Team

theme:
  name: material
  logo: assets/logo/vector/default-monochrome-white.svg
  favicon: assets/logo/profile.png
  
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.footer
    - toc.follow
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - content.action.edit

plugins:
  - search:
      separator: '[\s\-\.]+'

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - tables
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/agenticraft
    - icon: fontawesome/brands/discord
      link: https://discord.gg/agenticraft
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/agenticraft

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: quickstart.md
    - Configuration: getting-started/configuration.md
    - Your First Agent: getting-started/first-agent.md

  - Core Concepts:
    - Philosophy: philosophy.md
    - Agents: concepts/agents.md
    - Tools: concepts/tools.md
    - Workflows: concepts/workflows.md
    - Memory: concepts/memory.md
    - Reasoning: concepts/reasoning.md

  - Features:
    - Provider Switching: features/provider_switching.md
    - Advanced Agents: features/advanced_agents.md
    - MCP Integration: features/mcp_integration.md

  - Examples:
    - Overview: examples/index.md
    - Hello World: examples/hello-world.md
    - Provider Switching: examples/provider-switching.md
    - Advanced Agents: examples/advanced-agents.md
    - Real-World Apps: examples/real-world.md

  - API Reference:
    - Overview: reference/index.md
    - Agent: reference/agent.md
    - Tool: reference/tool.md
    - Workflow: reference/workflow.md
    - Providers:
      - OpenAI: reference/providers/openai.md
      - Anthropic: reference/providers/anthropic.md
      - Ollama: reference/providers/ollama.md
    - v0.1.1 Summary: reference/api-v0.1.1.md

  - Guides:
    - Performance Tuning: guides/performance-tuning.md

  - Plugins:
    - Creating Plugins: plugins/creating-plugins.md

  - Changelog: changelog.md
