blank_issues_enabled: false
contact_links:
  - name: Discord Community
    url: https://discord.gg/agenticraft
    about: Please ask and answer questions here.
  - name: Security Issues
    url: mailto:security@agenticraft.ai
    about: Please report security vulnerabilities here.
