# ServiceMonitor for Prometheus
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: agenticraft-codereview-monitor
  namespace: agenticraft
  labels:
    app: agenticraft
    component: monitoring
spec:
  selector:
    matchLabels:
      app: agenticraft
      component: codereview-api
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    honorLabels: true

---
# PodMonitor for additional metrics
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: agenticraft-pods-monitor
  namespace: agenticraft
  labels:
    app: agenticraft
    component: monitoring
spec:
  selector:
    matchLabels:
      app: agenticraft
  podMetricsEndpoints:
  - port: http
    path: /metrics
    interval: 30s
