# Development Deployment Patches
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agenticraft-codereview-api
spec:
  template:
    spec:
      containers:
      - name: api
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agenticraft-webhook-receiver
spec:
  template:
    spec:
      containers:
      - name: webhook
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "250m"
