"""Research Team Workflow - Generated by Visual Builder"""

import asyncio
from agenticraft.workflows import ResearchTeam

async def main():
    # Create research team
    team = ResearchTeam(
        size=5,
        model="gpt-4",
        name="ResearchTeam"
    )
    
    # Execute research
    report = await team.research(
        topic="Enter your research topic",
        depth="comprehensive",
        audience="general"
    )
    
    # Output results
    print("Executive Summary:")
    print(report["executive_summary"])
    print("\nKey Findings:")
    for finding in report["key_findings"]:
        print(f"- {finding}")

if __name__ == "__main__":
    asyncio.run(main())
